"""
Real NGO escalation email for Sahayak, via stdlib smtplib + a Gmail App
Password over STARTTLS. Gated by SEND_REAL_EMAILS so the pipeline defaults
to draft-only (today's behavior) until explicitly turned on.

Never raises: a failed send is logged and reported back as
(False, error_message) so it can never take down the agent pipeline.
"""
import logging
import os
import smtplib
import sys
from email.message import EmailMessage
from typing import Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config.settings import (
    SEND_REAL_EMAILS,
    SMTP_HOST,
    SMTP_PORT,
    SMTP_USER,
    SMTP_APP_PASSWORD,
)

logger = logging.getLogger("sahayak.email")


def send_ngo_escalation_email(
    to_email: str,
    ngo_name: str,
    case_id: str,
    message_body: str,
) -> Tuple[bool, Optional[str]]:
    """
    Sends the NGO Coordinator's escalation message to the chosen NGO.

    Returns (sent, error). `sent` is False whenever SEND_REAL_EMAILS is off
    (draft-only mode) or the send fails for any reason - `error` then holds
    a short reason string for the case log.
    """
    if not SEND_REAL_EMAILS:
        return False, "SEND_REAL_EMAILS is false (draft-only mode)"

    if not SMTP_USER or not SMTP_APP_PASSWORD:
        logger.warning("Email send skipped: SMTP_USER/SMTP_APP_PASSWORD not configured")
        return False, "SMTP credentials not configured"

    msg = EmailMessage()
    msg["Subject"] = f"Sahayak Helpline Escalation - Case {case_id}"
    msg["From"] = SMTP_USER
    msg["To"] = to_email
    msg.set_content(
        f"Dear {ngo_name},\n\n{message_body}\n\n"
        f"Case reference: {case_id}\n\n"
        "This escalation was generated by the Sahayak helpline agent."
    )

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_APP_PASSWORD)
            server.send_message(msg)
        return True, None
    except Exception as e:
        logger.error(f"Failed to send NGO escalation email for case {case_id}: {e}")
        return False, str(e)
